name: Apply Peribolos
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Apply-peribolos:
    if: ${{ github.repository_owner == 'complytime-labs' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout complytime-labs/.github repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: './go.mod'

      - name: Copy peribolos.yaml
        run: cp peribolos.yaml /tmp

      - name: Checkout ghproxy and peribolos code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: kubernetes-sigs/prow

      - name: Build ghproxy and peribolos
        env:
          GOTOOLCHAIN: auto
        run: |
          cd cmd/ghproxy && go mod tidy && go build -o /tmp/ghproxy . && cd ../..
          cd cmd/peribolos && go mod tidy && go build -o /tmp/peribolos . && cd ../..

      - name: Apply peribolos.yaml
        env:
          APP_ACCESS_TOKEN: ${{ secrets.APP_ACCESS_TOKEN }}
        run: |
          /tmp/ghproxy --legacy-disable-disk-cache-partitions-by-auth-header=false --get-throttling-time-ms=300 --throttling-time-ms=900 --throttling-time-v4-ms=850 --throttling-max-delay-duration-seconds=45 --throttling-max-delay-duration-v4-seconds=110 --request-timeout=120 1>/dev/null 2>&1 &
          pid=$!
          jobs
          /tmp/peribolos --config-path /tmp/peribolos.yaml --fix-org --fix-org-members --fix-teams --fix-team-members --fix-repos --fix-team-repos --min-admins 2 --github-token-path <(printf '%s' "$APP_ACCESS_TOKEN") --confirm 2>&1 | jq -r '[.severity, .time, .msg] | join(" | ")'
          kill $pid
